#=======
#シード値は0,1,,,
seed = 1
#平均次数　初期値は４
average_degree = 2
#ノード数　初期値は
num_nodes = 1000
#クラスタリング手法 JBGNNなら1,MinCutPoolなら0
jbgnn = 0
#======

import os.path as osp
import torch

import torch_geometric.transforms as T
from torch_geometric.datasets import Planetoid
from torch_geometric.nn import GCNConv, Sequential
from torch_geometric.nn.models.mlp import MLP
from torch_geometric import utils

from sklearn.metrics import normalized_mutual_info_score as NMI

from just_balance import just_balance_pool

#MinCutPoolのコードから移植
from torch.nn import Linear
from torch_geometric.nn import GraphConv, dense_mincut_pool
from torch_geometric.nn.conv.gcn_conv import gcn_norm

#DMoN
from torch_geometric.nn import DMoNPooling

#ACCの計算に必要
import numpy as np
from scipy.optimize import linear_sum_assignment

from sklearn.metrics import f1_score

import networkx as nx
from torch_geometric.utils import to_networkx, from_networkx, to_dense_adj

from torch_geometric.data import Data

from sklearn.metrics.cluster import pair_confusion_matrix

import sys

from torch_geometric.datasets import WebKB, WikipediaNetwork, KarateClub

import random


#seed = 1
torch.manual_seed(seed) # for (inconsistent) reproducibility
torch.cuda.manual_seed(seed)

random.seed(seed)#特徴量生成を固定するために追加した
np.random.seed(seed)#

# Load dataset choise:

#引用ネットワーク
#dataName = 'pubmed' #'cora', 'citeseer' or 'pubmed'
#path = osp.join(osp.dirname(osp.realpath(__file__)), '.', 'data', dataName)
#dataset = Planetoid(path, dataName, transform=T.NormalizeFeatures())
#data = dataset[0]

#Webページのリンクのネットワーク
#dataName = 'Cornell' #'Cornell','Texas','Wisconsin'
#dataset = WebKB(root='data/WebKB',name= dataName)
#data = dataset[0]

#Wikipediaのページ間のネットワーク
#dataName = 'squirrel' #'chameleon','squirrel'
#dataset = WikipediaNetwork(root='data/Wikipedia',name= dataName)
#data = dataset[0]

#空手クラブの交友関係ネットワーク
#dataset = KarateClub()
#data = dataset[0]
#dataName = 'KarateClub'

#人口ネットワーク生成

# ==================================================
# LFR Benchmark生成
# muは外部の辺/全辺
# average_degreeによって変の数も変動する
# min_comunityとmax_comunityの大きさとノード数の比によってある程度コミュニティ数を制御可能
# ==================================================
dataName = 'Generated by LFR Benchmark'

#num_nodes = 500 #coraは2700くらい　変化させる
target_clusters = 6 #coraは７
mu = 0.3 #coraは0.3付近　変動させるなら0.1(クラスタが明確)~0.5(クラスタが結構曖昧)
#average_degree = 4 #coraは4付近　変化させる

G = nx.LFR_benchmark_graph(
    n=num_nodes,
    tau1=2.5,
    tau2=1.5,
    mu=mu,
    average_degree=average_degree,
    max_degree=int(num_nodes/20),
    min_community=int(0.8 * (num_nodes / target_clusters)),
    max_community=int(1.2 * (num_nodes / target_clusters)),
    seed=seed
)
# ==================================================
# コミュニティラベル取得
# ==================================================
communities = {
    frozenset(G.nodes[v]["community"])
    for v in G.nodes()
}

labels = {}

for cid, community in enumerate(communities):
    for node in community:
        labels[node] = cid

num_clusters = len(communities)
# ==================================================
# PyGへ変換
# ==================================================
data = from_networkx(G)
# ==================================================
# 特徴量生成
# feature_dimで特徴ベクトルの次元数を決定
# noise_stdで同一クラスタ内の特徴ベクトルのばらつき具合を制御
# ==================================================
feature_dim = 1433

centers = torch.randint(
    0, 2,
    (num_clusters, feature_dim)
).float()

noise_std = 0.10

x = torch.zeros(num_nodes, feature_dim)

for node in range(num_nodes):
    c = labels[node]
    x[node] = centers[c] + noise_std * torch.randn(feature_dim)

data.x = x
# ==================================================
# ラベル
# ==================================================
data.y = torch.tensor(
    [labels[i] for i in range(num_nodes)],
    dtype=torch.long
)
# ==================================================
# Planetoid互換Dataset
# ==================================================
class SyntheticDataset:
    def __init__(self, data):
        self.data = data
        self.num_features = data.num_node_features
        self.num_classes = int(data.y.max()) + 1

    def __getitem__(self, idx):
        if idx != 0:
            raise IndexError
        return self.data

    def __len__(self):
        return 1


dataset = SyntheticDataset(data)
data = dataset[0]
# =============================================

#クラスタリング手法
#JBGNN
#jbgnn = 1
#MinCutPool
if jbgnn:
    minCut = 0
else:
    minCut = 1


#隣接行列の正規化には最初はMinCutPoolで使われる簡素なものを採用したが、GCNと相性がいいのは元の方法の方なのではないかとも思ったので変えた

#Compute connectivity matrix
delta = 0.85 #0.80に変更すると、MinCutでPubmedのクラスタリングがエラーにならず進んだ
edge_index, edge_weight = utils.get_laplacian(data.edge_index, data.edge_weight, normalization='sym')
L = utils.to_dense_adj(edge_index, edge_attr=edge_weight)
A = torch.eye(data.num_nodes) - delta*L
data.edge_index, data.edge_weight = utils.dense_to_sparse(A)

# Normalized adjacency matrix
#data.edge_index, data.edge_weight = gcn_norm(  
#               data.edge_index, data.edge_weight, data.num_nodes,
#               add_self_loops=False, dtype=data.x.dtype)



class Net(torch.nn.Module):
    def __init__(self, 
                 mp_units,
                 mp_act,
                 in_channels, 
                 n_clusters, 
                 mlp_units=[],
                 mlp_act="Identity"):
        super().__init__()
        
        mp_act = getattr(torch.nn, mp_act)(inplace=True)
        mlp_act = getattr(torch.nn, mlp_act)(inplace=True)

        #JBGNNのサンプルでは本来、(GCNConv(in_channels, mp_units[0], normalize=False, cached=False), 'x, edge_index, edge_weight -> x')を使用するが、
        #MinCutPoolのサンプルではGrahpConvを使用
        #DMoNのサンプルでは一層目はGCNConv、２層と３層ではDenseGraphConvを使用
        
        # Message passing layers
        if 1:
          #GCNConv
          mp = [
              (GCNConv(in_channels, mp_units[0], normalize=False, cached=False), 'x, edge_index, edge_weight -> x'),
              mp_act
          ]
          for i in range(len(mp_units)-1):
            mp.append((GCNConv(mp_units[i], mp_units[i+1], normalize=False, cached=False), 'x, edge_index, edge_weight -> x'))
            mp.append(mp_act)
          self.mp = Sequential('x, edge_index, edge_weight', mp)
          out_chan = mp_units[-1] 
          
        if 0:
          #GraphConv
          mp = [
              (GraphConv(in_channels, mp_units[0]), 'x, edge_index, edge_weight -> x'),
              mp_act
          ]
          for i in range(len(mp_units)-1):
            mp.append((GraphConv(mp_units[i], mp_units[i+1]), 'x, edge_index, edge_weight -> x'))
            mp.append(mp_act)
          self.mp = Sequential('x, edge_index, edge_weight', mp)
          out_chan = mp_units[-1]
        

        #MLP(多層パーセプトロン)を作成する
        self.mlp = MLP([out_chan] + mlp_units + [n_clusters], act=mlp_act, norm=None)
        
    def forward(self, x, edge_index, edge_weight):
        
        # Propagate node feats
        x = self.mp(x, edge_index, edge_weight)
        
        # Cluster assignments (logits)
        s = self.mlp(x)

        if jbgnn:#JBGNN
          # Compute loss
          adj = utils.to_dense_adj(edge_index, edge_attr=edge_weight)
          _, _, b_loss = just_balance_pool(x, adj, s)
        
          return torch.softmax(s, dim=-1), b_loss
          
        if minCut:#MinCutPool
          # Compute loss
          adj = utils.to_dense_adj(edge_index, edge_attr=edge_weight)
          _, _, mc_loss, o_loss = dense_mincut_pool(x, adj, s)

          total_loss = mc_loss + o_loss
      
          return torch.softmax(s, dim=-1), total_loss

        if 0:#DMoN
          #DMoNPooling([hidden_channels, hidden_channels], num_nodes) を使ってDMoN法に変更したい
          #論文では、ドロップアウトは0.5に設定　初期値は0.0
            
          # Compute loss
          k = 7 #Coraの場合は真のクラスタ数は7,
          #_, _, _, _, mo_loss, co_loss = DMoNPooling(edge_index.tolist(), k)
          _, _, _, _, mo_loss, co_loss = DMoNPooling(2708, k)

          total_loss = mo_loss + co_loss
      
          return torch.softmax(s, dim=-1), total_loss
        


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
data = data.to(device)
#MinCutPoolのサンプルでは活性化関数にELUを使用している
model = Net([64]*10, "ReLU", dataset.num_features, dataset.num_classes, [16], "ReLU").to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

def train():
    model.train()
    optimizer.zero_grad()
    _, loss = model(data.x, data.edge_index, data.edge_weight)
    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def test():
    model.eval()
    clust, _ = model(data.x, data.edge_index, data.edge_weight)
        
    return NMI(clust.max(1)[1].cpu(), data.y.cpu()), ACC(clust.max(1)[1].cpu(), data.y.cpu()),len(set(clust.max(1)[1].cpu().numpy().astype(np.int64)))

def ACC(y_pred, y_true):
    """
    クラスタリング ACC を Hungarian Algorithm で計算
    """
    pred = y_pred.cpu().numpy().astype(np.int64)
    true = y_true.cpu().numpy().astype(np.int64)
    
    D = max(pred.max(), true.max()) + 1
    w = np.zeros((D, D), dtype=int)

    for i in range(pred.size):
        w[pred[i], true[i]] += 1

    # Hungarian Algorithm
    row_ind, col_ind = linear_sum_assignment(w.max() - w)

    return sum(w[row, col] for row, col in zip(row_ind, col_ind)) / pred.size


def clustering_full_scores(y_pred, y_true, edge_index, num_nodes):
    """
    Hungarian ACC + F1 + Modularity + Conductance
    """
  
    # -----------------------------
    # ラベル整形
    # -----------------------------
    pred = y_pred.cpu().numpy().astype(np.int64)
    true = y_true.cpu().numpy().astype(np.int64)

    # -----------------------------
    # Hungarian 用行列
    # -----------------------------
    D = max(pred.max(), true.max()) + 1
    w = np.zeros((D, D), dtype=int)

    for i in range(pred.size):
        w[pred[i], true[i]] += 1

    row_ind, col_ind = linear_sum_assignment(w.max() - w)

    # -----------------------------
    # ラベル整列
    # -----------------------------
    label_map = {row: col for row, col in zip(row_ind, col_ind)}
    pred_aligned = np.vectorize(lambda x: label_map.get(x, x))(pred)

    # -----------------------------
    # F1
    # -----------------------------
    pcm = pair_confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = pcm.ravel()

    precision = tp / (tp + fp + 1e-12)
    recall    = tp / (tp + fn + 1e-12)

    f1_score = 2 * precision * recall / (precision + recall + 1e-12)

    # -----------------------------
    # Modularity
    # -----------------------------
    data_like = Data(edge_index=edge_index, num_nodes=num_nodes)
    G = to_networkx(data_like, to_undirected=True)

    communities = {}
    for node, c in enumerate(pred_aligned):
        communities.setdefault(int(c), set()).add(node)

    mod = nx.algorithms.community.quality.modularity(
        G, list(communities.values())
    )

    # -----------------------------
    # Conductance
    # -----------------------------
    adj = to_dense_adj(edge_index, max_num_nodes=num_nodes)[0]
    labels_t = torch.tensor(pred_aligned)

    cond_scores = []

    for c in labels_t.unique():
        S = (labels_t == c)
        notS = ~S

        cut = adj[S][:, notS].sum()
        volS = adj[S].sum()
        volNotS = adj[notS].sum()

        denom = torch.min(volS, volNotS)
        if denom > 0:
            cond_scores.append((cut / denom).item())

    conductance = float(np.mean(cond_scores)) if cond_scores else 0.0

    # -----------------------------
    return float(f1_score),mod,conductance

    
for epoch in range(1, 1001):#元は(1,1001)
    train_loss = train()
    nmi, acc, clust_types = test()
    #print(f'Epoch: {epoch:03d}, Loss: {train_loss:.4f}, ' f'NMI: {nmi:.4f}, ' f'ACC: {acc:.4f}, clust_types: {clust_types:.0f}')


model.eval()
clust, _ = model(data.x, data.edge_index, data.edge_weight)
f1_score,mod,conductance = clustering_full_scores(clust.max(1)[1].cpu(), data.y.cpu(),data.edge_index, data.num_nodes)
f1_score = float(f1_score)
#print(f'F1_score: {f1_score:.4f}, Modularity: {mod:.4f}, Conductance: {conductance:.4f}')
if jbgnn:
    print("clustering by JBGNN")
if minCut:
    print("clustering by MinCutPool")
#print(dataName)
#print(f'average_degree:{average_degree},num_nodes:{G.number_of_nodes()},num_edges:{G.number_of_edges()},true_num_clusters:{dataset.num_classes}')
print(f'average_degree:{average_degree},num_nodes:{G.number_of_nodes()},NMI:{nmi:.4f},seed:{seed}')


sys.exit()
